[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pypgfplots"
version = "0.1.7"
description = "Minimal pgfplots wrapper for marimo notebooks"
license = { text = "MIT" }
requires-python = ">=3.10"
readme = "README.md"

[project.urls]
Repository = "https://github.com/bjoseru/pypgfplots"

[tool.hatch.build.targets.wheel]
packages = ["pypgfplots"]

[tool.pytest.ini_options]
testpaths = ["tests"]
